remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: We Built Cathedrals
description: If you build it, it will be built.